apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-app
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgres-pod
    app: demo-app
