apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    name: voting-deployment
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-pod
      app: demo-app
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-pod
        app: demo-app
    spec:
      containers:
        - name: voting-container
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
